Title =  "Chao Yang"
LanguageCode = "en-us"
BaseUrl = "/"
Theme =  "m10c"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 20
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
PygmentsUseClasses = true
PygmentsCodeFences = true
DefaultContentLanguage = "en"
googleAnalytics = "UA-178463256-1"

[Params]
  Introduce = "Programmer & Life explorer"
  Description = "Developer ❤️ New Zealand"
  Keywords =  "Java, Programming, Android, JavaScript, Angular, Kotlin, Swift, iOS, Machine Learning, Big Data"
  Subtitle = "Nothing seek, nothing find"
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006"
  MonthFormat = "01-02"
  Fancybox = true
  Version = "0.74.3"

[Author]
  Name = "Chao"

[Params.Share]
  Baidu = false
  Weixin = false

[[Menu.Main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "Dev"
  Pre = "code"
  URL = "https://github.com/chaoyangnz"
  Weight = 2
[[Menu.Main]]
  Name = "CV"
  Pre = "linkedin"
  URL = "/resume/cv.pdf"
  Weight = 3
[[Menu.Main]]
  Name = "Minibooks"
  Pre = "book"
  URL = "/books"
  Weight = 4
[[Menu.Main]]
  Name = "About"
  Pre = "user"
  URL = "/about/"
  Weight = 5
[[Menu.Main]]
  Name = "Archive"
  Pre = "archive"
  URL = "/archive"
  Weight = 6

[[Params.Social]]
  name = "github"
  url = "https://github.com/chaoyangnz"

[[Params.Social]]
  name = "linkedin"
  url = "https://linkedin.com/in/chaoyangnz"  

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"  

avatar = "https://avatars3.githubusercontent.com/u/4645331"

