backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: content/media
public_folder: /media
collections:
  - name: 'post'
    label: 'Blog'
    folder: 'content/post'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
